# Generated by Django 3.0.6 on 2021-09-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0003_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qrcode',
        ),
        migrations.AddField(
            model_name='product',
            name='AR',
            field=models.URLField(blank=True),
        ),
    ]
